language: node_js
dist: trusty

node_js:
 - "0.12"
 - "0.10"
 - "4.1.1"
 - "5.1.0"
 - "6.4.0"

before_install:  
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' > /etc/apt/sources.list.d/mono-xamarin.list"
 - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
 - sudo sh -c "echo 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main' > /etc/apt/sources.list.d/dotnetdev.list"
 - sudo apt-get update

install:
 - sudo apt-get install mono-devel dotnet-dev-1.0.0-preview2-003131
 - npm install -g grunt-cli

script:
 - dotnet build -c Release -f netstandard1.6 src/double/Edge.js
 - cp src/double/Edge.js/bin/Release/netstandard1.6/EdgeJs.dll src/double/Edge.js/bin/Release/net40/EdgeJs.dll
 - dotnet pack -c Release --no-build src/double/Edge.js
 - dotnet restore lib/bootstrap -f src/double/Edge.js/bin/Release
 - npm install
 - npm test
 - EDGE_USE_CORECLR=1 EDGE_DEBUG=1 npm test